blank_issues_enabled: false
issue_templates:
- name: Task
  description: Create a task issue template
  file: task.yml
- name: Bug
  description: Create a bug issue template
  file: bug.yml
- name: Feature
  description: Create a feature issue template
  file: feature.yml
- name: Epic
  description: Create an epic issue template
  file: epic.yml
- name: Spike
  description: Create a spike issue template
  file: spike.yml
- name: Enhancement
  description: Create an enhancement issue template
  file: enhancement.yml
- name: Chore
  description: Create a chore issue template
  file: chore.yml
