name: 🔧 Enhancement
description: Create an enhancement issue template
title: "[Enhancement] <title>"
labels: ["Enhancement"]
projects: ["WebifyServices/24"]
type: Enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: "What needs to be improved and why?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: "Describe the current state of the feature."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Updated Behavior
      description: "Describe the desired state of the feature."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: "Define what needs to be true for this enhancement to be considered complete."
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
  - type: textarea
    attributes:
      label: References and Media
      description: "Attach relevant links and/or media to illustrate the enhancement."
    validations:
      required: false
