name: 🔎 Spike
description: Create a spike issue template
title: "[Spike] <title>"
labels: [ "Spike" ]
projects: [ "WebifyServices/24" ]
type: Spike
body:
- type: textarea
  attributes:
    label: Description
    description: "What needs to be investigated or researched?"
  validations:
    required: true
- type: textarea
  attributes:
    label: Objectives
    description: "What are the goals or outcomes of this spike?"
  validations:
    required: true
- type: textarea
  attributes:
    label: Context
    description: "Any relevant background or information for this spike."
  validations:
    required: false
- type: textarea
  attributes:
    label: Deliverables
    description: "What is expected at the end of this spike?"
    value: |
      - Finding 1
      - Recommendation 2
  validations:
    required: true
