name: ✅ Task
description: Create a task issue template
title: "[Task] <title>"
labels: [ "Task" ]
projects: [ "WebifyServices/24" ]
type: Task
body:
- type: textarea
  attributes:
    label: Description
    description: "What needs to be done?"
  validations:
    required: true
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: "Define what needs to be true for this task to be considered complete."
    value: |
      - [ ] Criterion 1
      - [ ] Criterion 2
  validations:
    required: true
- type: textarea
  attributes:
    label: Context
    description: "Any relevant background or information for completing this task."
  validations:
    required: false
